*MAT_FABRIC_MAP_TITLE
$#
?title?
$#     mid        ro       pxx       pyy       sxy      damp        th
         ?         ?         ?         ?         ?
$#   fvopt        x0        x1    flc/x2    fac/x3       ela

$#  isrefg       cse     srfac     bulkc      jacc       fxx       fyy        dt

$#    aopt     ecoat     scoat     tcoat

$#      xp        yp        zp        a1        a2        a3

$#      v1        v2        v3        d1        d2        d3      beta

$