*MAT_VISCOELASTIC_LOOSE_FABRIC_TITLE
$#
?title?
$#     mid        ro        e1        e2       g12        eu       thl       thi
         ?         ?         ?         ?
$#      ta         w       spn         t         h         s       eka       eua
         ?
$#     vmb         c       g23       ekb      aopt

$#                                    a1        a2        a3

$#      v1         v2       v3        d1        d2        d3

$
